### ISSUE TITLE
A couple of notes on newsched and a question

### ISSUE THREAD

**Issue by fventuri** [gnuradio/newsched#165]
Josh,
I played around with newsched over the weekend and I noticed a couple of things:
  - I am running Fedora 35 here, and I had the same problem that Marcus found out with GRC here: https://github.com/gnuradio/gnuradio/issues/5216 - I applied the same changes he made in this PR: https://github.com/gnuradio/gnuradio/pull/5217 , and it fixed this problem
  - since newsched didn't create an `__init__.py` under `prefix/lib/python3.10/site-packages/gnuradio`, Python didn't recognize it a module, so it wouldn't find `gnuradio/grc` underneath - I just created an empty `__init__.py` there with 'touch', and that fixed it

Finally I have a question: when newsched GRC tries to load new blocks, it looks for them under `prefix/lib64/share/gnuradio/grc/blocks`, instead of `prefix/share/gnuradio/grc/blocks`, which is where `ninja install` puts them.
The reason seems to be somewhere among these lines in `constants.cc.in`: https://github.com/gnuradio/newsched/blob/main/runtime/lib/constants.cc.in#L30-L35

I added a few prints to see what those variables where set to here (my prefix is `/home/franco/SDR/newsched`):

```
prefix_rel_lib: ""
gr_runtime_lib_path: "/home/franco/SDR/newsched/lib64/libnewsched-runtime.so"
canonical_lib_path: "/home/franco/SDR/newsched/lib64/libnewsched-runtime.so"
prefix_path: "/home/franco/SDR/newsched/lib64/"
prefix_path.lexically_normal(): "/home/franco/SDR/newsched/lib64/"
prefix: /home/franco/SDR/newsched/lib64/
```

It almost seems like the variable `prefix_path` should have a second `parent_path()` to remove the `lib64` suffix, but maybe there's something else I am missing here.

Thanks for all your hard work on newsched (and GNU Radio, of course)!

Franco

**Comment by mormj** [comment]
@fventuri - thank you for the feedback here.  I will go ahead and fix the two issues you noted above (also feel free to submit PRs).  

That's interesting about the grc blocks path.  This code was mostly copied from GNU Radio so I may have missed some nuances.  I'll dig in and see if there is an easy way to sort this out.

Thanks!

**Comment by fventuri** [comment]
Thanks Josh
I pulled the latest version and I was able to start GRC without any errors.
Franco
