### ISSUE TITLE
Tags as PMT vectors

### ISSUE THREAD

**Issue by mormj** [gnuradio/newsched#190]
Right now tags are their own struct, which poses problems for default serialization

Is there any reason tags can't just be a PMT vector of PMTs or a pmt map?

**Comment by jacobagilbert** [comment]
Is the question whether individual tags should all be PMT vectors? Or whether the `tags` associated with an item should be a vector of PMT objects, each representing a tag?

**Comment by mormj** [comment]
Whether individual tags should be PMT vectors (or maps).  If the individual object is a PMT, then we get serialization for free.  I think @jsallay has other ideas for how to make PMTs of arbitrary types, but for tags I'm wondering if an existing construct is good enough

**Comment by jacobagilbert** [comment]
a vector is probably not a good choice for individual tags, it might be worth creating a derived map `tag` type PMT (john would know better than I) but maps would be reasonable; tags are metadata and this would be consistent with PDU structure.
